### ISSUE TITLE
Provide snap or flatpak package 

### ISSUE THREAD

**Issue by wagner-ch** [karakun/OpenWebStart#602]
Currently there is only a .deb package to install Openwebstart on Ubuntu. Would be nice to have a Snap and/or Flatpak package in order to support more that one linux distribution.

**Comment by amandasystems** [comment]
I'm interested in working on this. Are PRs welcome?

**Comment by sclassen** [comment]
Yes, PRs are welcome.

We currently support only .deb because we do not have the resources to test and maintain multiple linux packages.

In that sense before you invest too much time into this we should come up with a concept of how we can integrate the creation and distribution of snap or flatpack artifacts in our release process.

If you are still interested, I can lay out our release process for you.

**Comment by amandasystems** [comment]
I’ll take a stab at doing the flatpak first since I kind of want it for myself. If I get it running I’ll get back to you!

The dream would of course be something automated that publishes to flathub. This is something a lot of projects do so it doesn’t seem impossible.

**Comment by amandasystems** [comment]
Update on my stab: I gave up when I needed maven for building but there was no package for maven and building maven required maven. At that point the yak shaving got too intense even for me. 

I’ll add the build file I had when I gave up because I don’t think it’s a terrible starting point assuming you can somehow get maven into the build system. Maybe someone comes around with the patience for the Java ecosystem to pull it off.

```yaml
id: com.openwebstart.OpenWebStart
runtime: org.freedesktop.Platform
runtime-version: '25.08'
sdk: org.freedesktop.Sdk
sdk-extensions:
  - org.freedesktop.Sdk.Extension.openjdk8
command: hello

finish-args:
  - --socket=x11
  - --share=ipc
  - --env=PATH=/app/jre/bin:/app/bin:/usr/bin
  - --env=JAVA_HOME=/app/jre
  # ...

modules:
  #- name: openjdk
  #  buildsystem: simple
  #  #build-commands:
  #  #  - /usr/lib/sdk/openjdk8/install.sh
  - name: icedteaweb
    buildsystem: simple
    build-options:
      env:
        PATH: /app/bin:/usr/bin:/usr/lib/sdk/openjdk8/bin
        JAVA_HOME: /usr/lib/sdk/openjdk8/jvm/java-8-openjdk
    build-commands:
        - mvn install
    sources:
      - type: git
        url: https://github.com/AdoptOpenJDK/IcedTea-Web

  - name: openwebstart
    buildsystem: simple
    build-options:
      env:
        PATH: /app/bin:/usr/bin:/usr/lib/sdk/openjdk8/bin
        JAVA_HOME: /usr/lib/sdk/openjdk8/jvm/java-8-openjdk
    build-commands:
      - ./mvnw install
      - install -Dm755 -t /app/bin myapp
      - install -Dm644 -t /app/share/com.example.myapp myapp.jar
      # ...
    sources:
      - type: archive
        url: https://github.com/karakun/OpenWebStart/archive/refs/tags/v1.14.0.tar.gz
        sha256: d031698f1c1d33de9a19790ed6ce95e292a611802f8c1fcf53906863a3a3ab90
        # ...
      - type: script
        dest-filename: myapp
        commands:
          - exec java -jar /app/share/com.example.myapp/myapp.jar $@
      # ...

```
